name: Compile Latex and Release PDF

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          # working_directory: skripsi
          root_file: |
            # thesis.tex
            proposal.tex

      - name: Check if PDF exists
        run: |
          ls ${{ github.workspace }}/thesis

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            # thesis.pdf
            proposal.pdf
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
