name: Compile Latex and Release PDF

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          # working_directory: skripsi
          root_file: |
            proposal.tex

      - name: Check if PDF exists
        run: |
          ls ${{ github.workspace }}/
          FILE=${{ github.workspace }}/thesis.pdf
          test -f "$file" || echo "$file"

      - name: Create Artifact On Pull Request
        if: ${{ github.event_name == 'push' }}
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifacts-branch: pdf-dump
          artifacts: |
            ${{ github.workspace }}/proposal.pdf
